server.port=6262
spring.application.name=music-catlog-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/music_catalog
spring.datasource.username=music_admin
spring.datasource.password=changeme_local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
itunes.api.base-url=https://itunes.apple.com/search